#!/bin/bash

iteration_printout() {
    printf "=============================\n\n"
    date
    printf "    Ping Attempt # $2\n\n"
    ping $1 -c 10
    printf "\n=============================\n\n"
}

if [ -z $1 ]; then
    echo "You need to set a number first."

elif [ -z $2 ]; then
    echo "Destination address required."

else

    if [[ $3 == "t" ]]; then
        isLog=1
    else
        isLog=0
    fi

    iterations=$1
    destination=$2
    
    echo "Enter Start of Counter: "
    read ctr
    
    idx=1
    current_timestamp=$(date +%Y-%m-%dT%H%M%S_Z%z | sed 's/+//')

    if [[ $isLog == 1 ]]; then
	    touch $HOME/Documents/Logs/ping-cont_${current_timestamp}.txt
    fi

    while [ $idx -le $iterations ]; do
        trap exit SIGINT SIGTERM
        if [[ $isLog == 1 ]]; then
            iteration_printout $destination $idx | tee -a $HOME/Documents/Logs/ping-cont_${current_timestamp}.txt
        else 
            iteration_printout $destination $idx
        fi
	((idx++))
    done
fi
