#!/bin/bash

iteration_printout() {
        printf "=============================\n\n"
        date
        printf "    Speedtest Attempt # $ctr\n\n"
        speedtest || speedtest-cli
        printf "\n=============================\n\n"
        idx=$(( idx+1 ))
        ctr=$(( ctr+1 )) 
}

if [ -z $1 ]; then
    echo "You need to set a number first"

else
    
    echo "Enter Start of Counter: "
    read ctr
    
    idx=1
    current_timestamp=$(date +%Y-%m-%dT%H%m%s_Z%z | sed 's/+//')

    while [ $idx -le $1 ]; do
        trap exit SIGINT SIGTERM
        iteration_printout $1 | tee -a ~/Documents/Logs/ping-cont_$current_timestamp.txt
    done
fi
