theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
# mouse = false 
bufferline = "multiple"

[keys.normal]
# No Keybindings 
C-c = "no_op"

esc = ["collapse_selection", "keep_primary_selection"]
"C-/" = "toggle_comments"

# Custom Space Mode Keybindings 

# config keybindings <space>c 
[keys.normal.space.c]
# <space>cc    open config 
c =  [":config-open"]
# c = { label = "Open Configuration File", command = [":config-open"] } 
# <space>cs    save config and reload 
s = [":w", ":config-reload"]

# buffer keybindings g 
[keys.normal.g]
p = "no_op"
n = "no_op"
# gH           go to previous buffer 
H = "goto_previous_buffer"
# gL           go to next buffer 
L = "goto_next_buffer"

[editor.cursor-shape]
insert = "bar"