#!/bin/bash

iteration_printout() {
    printf "=============================\n\n"
    date
    printf "    Ping Attempt # $ctr\n\n"
    ping $1 -c 10
    printf "\n=============================\n\n"
    idx=$(( idx+1 ))
    ctr=$(( ctr+1 ))
}

if [ -z $1 ]; then
    echo "You need to set a number first."

elif [ -z $2 ]; then
    echo "Destination address required."

else

    if [[ $3 == "t" ]]; then
        isLog=1
    else
        isLog=0
    fi
    
    echo "Enter Start of Counter: "
    read ctr
    
    idx=1
    current_timestamp=$(date +%Y-%m-%dT%H%M%S_Z%z | sed 's/+//')

    while [ $idx -le $1 ]; do
        trap exit SIGINT SIGTERM
        if [[ $isLog == 1 ]]; then
            iteration_printout $2 | tee $HOME/Documents/__Documents/Logs/${current_timestamp}-ping.txt
        else 
            iteration_printout $2
        fi
    done
fi
